apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "r-shiny-proxy.fullname" . }}
spec:
  selector:
    matchLabels:
      run: {{ include "r-shiny-proxy.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ include "r-shiny-proxy.fullname" . }}
    spec:
      containers:
      - name: {{ include "r-shiny-proxy.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.service.containerPort }}
      - name: {{ include "r-shiny-proxy.fullname" . }}-sidecar
        image: "{{ .Values.image.repositorySidecar }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always 
        ports:
        - containerPort: {{ .Values.service.sideContainerPort }}

