kind: Service
apiVersion: v1
metadata:
  name: shinyproxy
spec:
  type: NodePort
  selector:
    run: shinyproxy
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32094
---
apiVersion: v1
kind: Service
metadata:
  name: shinyproxy-load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    run: shinyproxy