proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: Elhay
    password: Elhay@123
    groups: admins
  - name: Gili
    password: Gili@123
    groups: admins
  - name: Noam
    password: Noam@123
  - name: Guest
    password: Guest@123
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: http://localhost:8001
    namespace: r-shiny-proxy 
    image-pull-policy: Always
  specs:
  - id: Demo
    display-name: Demo by region
    description: Demo which shows telephone by region
    container-image: tevaprivatedemo.azurecr.io/r-shiny-app:latest
    # access-groups: [scientists, mathematicians]
  - id: Gili
    display-name: Gili by region
    description: Gili which shows telephone by region
    container-image: tevaprivatedemo.azurecr.io/r-shiny-app:latest
    # access-groups: [scientists, mathematicians]
logging:
  file:
    shinyproxy.log
